### ISSUE TITLE
Which HTTP methods does the "redirect" route support?

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/urihandler#73]
```
@view_config(route_name='redirect')
def redirect(request):
    uri = request.host_url + '/' + request.matchdict['uri']
    redirect = request.uri_handler.handle(uri, request)
    if not redirect:
        raise HTTPNotFound()
    return HTTPSeeOther(redirect)
```

When I try to delete a resource when performing the DELETE method on the URI, then a 200 response is returned but my resource wasn't deleted. I expect a deleted resource and 204 (or 200) response, or better a 405 Method not allowed response.

I guess the route only has to work with a GET and HEAD method? So a 405 should be returned for any PUT, DELETE and POST on this route. 
Passing an Authorization header is not allowed in 303 Redirects so PUT, DELETE and POST will never have a usecase for this route.

**Comment by koenedaele** [comment]
HTTP 405 Method Not Allowed is the best solution. Partially because, to be semantically pedantically correct, the URI's served by the urihandler represent the concept of a thing, not the document about that thing. So, DELETE https://id.erfgoed.net/erfgoedobjecten/25890 actually means "Destroy the Gravensteen", not "Delete the record about the Gravensteen". Same for PUT and POST.
